# Generated by Django 4.2.4 on 2023-08-22 18:46

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bamie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidancetree',
            name='example_input_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidancetree',
            name='example_output_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('guidance_tree_node', models.IntegerField(default=0)),
                ('recieved_messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('suggested_messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('sent_messages', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('recieved_messages_timestamp', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('sent_messages_timestamp', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('guidance_tree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bamie.guidancetree')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
