# Generated by Django 4.2.4 on 2023-08-23 10:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamie', '0002_guidancetree_example_input_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='recieved_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='recieved_messages_timestamp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sent_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sent_messages_timestamp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='suggested_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='parents_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
