# Generated by Django 4.2.4 on 2023-08-23 10:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamie', '0003_alter_chatroom_recieved_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidancetree',
            name='parents_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
    ]
