# Generated by Django 4.2.4 on 2023-08-23 10:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamie', '0004_alter_guidancetree_parents_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='recieved_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='recieved_messages_timestamp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sent_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sent_messages_timestamp',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='suggested_messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
