# Generated by Django 4.2.4 on 2023-08-24 15:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamie', '0005_alter_chatroom_recieved_messages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidancetree',
            old_name='parents_array',
            new_name='parent_array',
        ),
        migrations.AddField(
            model_name='guidancetree',
            name='position_array_x_axis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidancetree',
            name='position_array_y_axis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0], size=None),
            preserve_default=False,
        ),
    ]
