# Generated by Django 4.2.4 on 2023-08-24 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamie', '0006_rename_parents_array_guidancetree_parent_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidancetree',
            name='example_input_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[''], size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='example_output_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[''], size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='parent_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), default=[-1], size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='position_array_x_axis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0], size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='position_array_y_axis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0], size=None),
        ),
    ]
