# Generated by Django 4.2.4 on 2023-08-24 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamie', '0007_alter_guidancetree_example_input_array_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidancetree',
            name='example_input_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='example_output_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='parent_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='position_array_x_axis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
        migrations.AlterField(
            model_name='guidancetree',
            name='position_array_y_axis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
